# Pre Clean Datasets from Jeff Sackmann Datasets

Imports

In [1]:
%matplotlib inline
import os
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
from collections import defaultdict
import re
import warnings

Import Datasets

In [ ]:
jeff_data = pd.DataFrame()
for year in range(1991, 2025):
    file = "./data/JeffSackmann/atp_matches_"+str(year)+".csv"
    
    year_data = pd.read_csv(file)

    jeff_data = pd.concat([jeff_data, year_data], axis=0)
    
jeff_data['tourney_date'] = pd.to_datetime(jeff_data['tourney_date'], format='%Y%m%d')

print(len(jeff_data))
jeff_data.head(5)

108375

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,1991-339,Adelaide,Hard,32,A,1990-12-31,1,101723,NaN,NaN,Magnus Larsson,R,193.0,SWE,20.7,101414,1.0,NaN,Boris Becker,R,190.0,GER,23.1,6-4 3-6 7-6(2),3,R32,130.0,6.0,2.0,96.0,55.0,39.0,25.0,15.0,2.0,4.0,8.0,3.0,95.0,62.0,44.0,23.0,16.0,6.0,8.0,56.0,NaN,2.0,NaN
1,1991-339,Adelaide,Hard,32,A,1990-12-31,2,100946,NaN,Q,Slobodan Zivojinovic,R,198.0,YUG,27.4,101256,NaN,NaN,Mark Kratzmann,L,178.0,AUS,24.6,6-3 3-6 7-6(6),3,R32,119.0,19.0,4.0,101.0,56.0,45.0,25.0,15.0,9.0,10.0,8.0,2.0,84.0,41.0,35.0,27.0,15.0,1.0,2.0,304.0,NaN,75.0,NaN
2,1991-339,Adelaide,Hard,32,A,1990-12-31,3,101234,NaN,NaN,Patrik Kuhnen,R,190.0,GER,24.8,101421,NaN,NaN,Veli Paloheimo,R,183.0,FIN,23.0,6-0 6-4,3,R32,71.0,6.0,1.0,54.0,31.0,24.0,13.0,8.0,1.0,1.0,2.0,2.0,60.0,37.0,22.0,6.0,8.0,4.0,8.0,82.0,NaN,69.0,NaN
3,1991-339,Adelaide,Hard,32,A,1990-12-31,4,101889,8.0,NaN,Todd Woodbridge,R,178.0,AUS,19.7,101703,NaN,NaN,Guillaume Raoux,R,180.0,FRA,20.8,7-6(2) 6-1,3,R32,85.0,2.0,0.0,60.0,40.0,30.0,14.0,9.0,3.0,3.0,3.0,3.0,74.0,45.0,30.0,11.0,10.0,5.0,8.0,50.0,NaN,84.0,NaN
4,1991-339,Adelaide,Hard,32,A,1990-12-31,5,101274,NaN,NaN,Udo Riglewski,R,185.0,GER,24.4,101843,4.0,NaN,Sergi Bruguera,R,188.0,ESP,19.9,7-5 6-3,3,R32,90.0,4.0,2.0,72.0,40.0,33.0,14.0,10.0,7.0,8.0,2.0,2.0,77.0,41.0,28.0,15.0,11.0,4.0,8.0,88.0,NaN,28.0,NaN

### Cleanup Rows

In [3]:
jeff_data = jeff_data.dropna(subset=['winner_id', 'winner_name'], how='all')
jeff_data = jeff_data.dropna(subset=['loser_id', 'loser_name'], how='all')
jeff_data = jeff_data.dropna(subset=['tourney_id', 'tourney_name'], how='all')
jeff_data = jeff_data.dropna(subset=['round', 'tourney_date'], how='any')

### Cleanup Columns
1. Drop Unnecessary
2. Rename

In [4]:
jeff_data = jeff_data.drop(columns=['winner_ioc', 'loser_ioc', 'winner_entry', 'loser_entry', 'winner_seed', 'loser_seed'], axis=1)
jeff_data = jeff_data.rename(columns={
    'winner_rank_points': 'winner_atp_points',
    'loser_rank_points': 'loser_atp_points',})

jeff_data.head(5)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_name,winner_hand,winner_ht,winner_age,loser_id,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_atp_points,loser_rank,loser_atp_points
0,1991-339,Adelaide,Hard,32,A,1990-12-31,1,101723,Magnus Larsson,R,193.0,20.7,101414,Boris Becker,R,190.0,23.1,6-4 3-6 7-6(2),3,R32,130.0,6.0,2.0,96.0,55.0,39.0,25.0,15.0,2.0,4.0,8.0,3.0,95.0,62.0,44.0,23.0,16.0,6.0,8.0,56.0,NaN,2.0,NaN
1,1991-339,Adelaide,Hard,32,A,1990-12-31,2,100946,Slobodan Zivojinovic,R,198.0,27.4,101256,Mark Kratzmann,L,178.0,24.6,6-3 3-6 7-6(6),3,R32,119.0,19.0,4.0,101.0,56.0,45.0,25.0,15.0,9.0,10.0,8.0,2.0,84.0,41.0,35.0,27.0,15.0,1.0,2.0,304.0,NaN,75.0,NaN
2,1991-339,Adelaide,Hard,32,A,1990-12-31,3,101234,Patrik Kuhnen,R,190.0,24.8,101421,Veli Paloheimo,R,183.0,23.0,6-0 6-4,3,R32,71.0,6.0,1.0,54.0,31.0,24.0,13.0,8.0,1.0,1.0,2.0,2.0,60.0,37.0,22.0,6.0,8.0,4.0,8.0,82.0,NaN,69.0,NaN
3,1991-339,Adelaide,Hard,32,A,1990-12-31,4,101889,Todd Woodbridge,R,178.0,19.7,101703,Guillaume Raoux,R,180.0,20.8,7-6(2) 6-1,3,R32,85.0,2.0,0.0,60.0,40.0,30.0,14.0,9.0,3.0,3.0,3.0,3.0,74.0,45.0,30.0,11.0,10.0,5.0,8.0,50.0,NaN,84.0,NaN
4,1991-339,Adelaide,Hard,32,A,1990-12-31,5,101274,Udo Riglewski,R,185.0,24.4,101843,Sergi Bruguera,R,188.0,19.9,7-5 6-3,3,R32,90.0,4.0,2.0,72.0,40.0,33.0,14.0,10.0,7.0,8.0,2.0,2.0,77.0,41.0,28.0,15.0,11.0,4.0,8.0,88.0,NaN,28.0,NaN

### Tournament ID formatting

1. Davis Cup Standardisation

In [5]:
def update_davis_cup_tourney_ids(df):
    """
    Update tourney_id for Davis Cup entries based on the word following 'Davis Cup'
    Finals: 430, G1/WG1/WG: 431, WG2/G2: 432, QLS: 433
    """
    # Create a copy to avoid modifying original
    df_updated = df.copy()
    
    # Extract Davis Cup entries
    davis_cup_mask = df_updated['tourney_name'].str.contains('Davis Cup', na=False, case=False)
    
    # Extract the word following "Davis Cup"
    pattern = r'Davis Cup\s+(\w+)'
    words_after = df_updated.loc[davis_cup_mask, 'tourney_name'].str.extract(pattern, flags=re.IGNORECASE)[0]
    
    # Create mapping based on the word
    for idx, word in words_after.items():
        if pd.isna(word):
            continue
        
        if word.upper() == 'FINALS':
            new_id = "430"
            new_name = "Davis Cup Finals"
        elif word.upper() in ['G1', 'WG1', 'WG']:
            new_id = "431"
            new_name = "Davis Cup World Group 1"
        elif word.upper() in ['WG2', 'G2']:
            new_id = "432"
            new_name = "Davis Cup World Group 2"
        elif word.upper() == 'QLS':
            new_id = "433"
            new_name = "Davis Cup Qualifiers"
        else:
            continue  # Keep original ID if no match
            
        df_updated.loc[idx, 'tourney_id'] = new_id
        df_updated.loc[idx, 'tourney_name'] = new_name
        df_updated.loc[idx, 'tourney_level'] = 'D'
    
    return df_updated

jeff_data = update_davis_cup_tourney_ids(jeff_data)

2. Olympics Standardisation

In [6]:
olympic_mask = jeff_data['tourney_name'].str.contains('Olympic', na=False, case=False)
jeff_data.loc[olympic_mask, 'tourney_level'] = 'O'
jeff_data.loc[olympic_mask, 'tourney_id'] = 4800

2. Dropping Year Prefix

In [7]:
def drop_year_prefix(df):
    """
    Drop everything up to and including the hyphen in tourney_id, only if hyphen exists
    """
    df_updated = df.copy()
    
    # Only split on hyphen if it exists
    mask_with_hyphen = df_updated['tourney_id'].str.contains('-', na=False)
    df_updated.loc[mask_with_hyphen, 'tourney_id'] = df_updated.loc[mask_with_hyphen, 'tourney_id'].str.split('-').str[1]
    
    return df_updated

# Apply the function
jeff_data = drop_year_prefix(jeff_data)

3. Remove Letters

In [8]:
def clean_tourney_id(tourney_id):
    """
    Remove any letters from tourney_id and replace with '0'.
    Keeps only digits, hyphens, and underscores.
    
    Examples:
        '2024-580' -> '2024-580'
        '580' -> '580'
        '580A' -> '5800'
        'WTA-2024' -> '0-2024'
        'ITF123M' -> '0012300'
    """
    if pd.isna(tourney_id):
        return tourney_id
    
    tourney_id_str = str(tourney_id)
    
    # Replace any letter (a-z, A-Z) with '0'
    cleaned = re.sub(r'[a-zA-Z]', '0', tourney_id_str)
    
    return cleaned

# Apply cleaning to tourney_id column
print("Before cleaning:")
print(f"  Total rows: {len(jeff_data)}")
print(f"  Null tourney_id: {jeff_data['tourney_id'].isna().sum()}")
print(f"  Sample tourney_ids: {jeff_data['tourney_id'].unique()[:20]}")

# Check which tourney_ids contain letters
ids_with_letters = jeff_data[jeff_data['tourney_id'].astype(str).str.contains(r'[a-zA-Z]', na=False)]
print(f"\nRows with letters in tourney_id: {len(ids_with_letters)}")
if len(ids_with_letters) > 0:
    print("Sample IDs with letters:")
    print(ids_with_letters[['tourney_id', 'tourney_name']].drop_duplicates().head(20))

# Apply cleaning
jeff_data['tourney_id'] = jeff_data['tourney_id'].apply(clean_tourney_id)

print("\nAfter cleaning:")
print(f"  Null tourney_id: {jeff_data['tourney_id'].isna().sum()}")
print(f"  Sample tourney_ids: {jeff_data['tourney_id'].unique()[:20]}")

# Verify no letters remain
ids_with_letters_after = jeff_data[jeff_data['tourney_id'].astype(str).str.contains(r'[a-zA-Z]', na=False)]
print(f"\nRows with letters after cleaning: {len(ids_with_letters_after)}")

if len(ids_with_letters_after) == 0:
    print("✓ All letters successfully removed from tourney_id!")

Before cleaning:
  Total rows: 108375
  Null tourney_id: 0
  Sample tourney_ids: ['339' '354' '301' '338' '580' '431' '432' '401' '402' '357' '411' '305'
 '434' '410' '456' '309' '717' '433' '414' '416']

Rows with letters in tourney_id: 808
Sample IDs with letters:
     tourney_id        tourney_name
0          M020            Brisbane
112        M001              Sydney
490        M052      Rio de Janeiro
521        M004            Acapulco
1187       M021      Madrid Masters
1242       M009        Rome Masters
1478       M010     s Hertogenbosch
2006       M035          Washington
2226       M024  Cincinnati Masters
1695       M016          Eastbourne
2571       M015             Beijing
113        M056            Adelaide

After cleaning:
  Null tourney_id: 0
  Sample tourney_ids: ['339' '354' '301' '338' '580' '431' '432' '401' '402' '357' '411' '305'
 '434' '410' '456' '309' '717' '433' '414' '416']

Rows with letters after cleaning: 0
✓ All letters successfully removed from tourney_id!

4. Ensure 4 Digit Length

In [9]:
jeff_data.copy().assign(
    tourney_id=jeff_data['tourney_id'].apply(
        lambda x: str(x) + '0' * (4 - len(str(x))) if pd.notna(x) and len(str(x)) < 4 else x
    )
)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_name,winner_hand,winner_ht,winner_age,loser_id,loser_name,loser_hand,loser_ht,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_atp_points,loser_rank,loser_atp_points
0,3390,Adelaide,Hard,32,A,1990-12-31,1,101723,Magnus Larsson,R,193.0,20.7,101414,Boris Becker,R,190.0,23.1,6-4 3-6 7-6(2),3,R32,130.0,6.0,2.0,96.0,55.0,39.0,25.0,15.0,2.0,4.0,8.0,3.0,95.0,62.0,44.0,23.0,16.0,6.0,8.0,56.0,NaN,2.0,NaN
1,3390,Adelaide,Hard,32,A,1990-12-31,2,100946,Slobodan Zivojinovic,R,198.0,27.4,101256,Mark Kratzmann,L,178.0,24.6,6-3 3-6 7-6(6),3,R32,119.0,19.0,4.0,101.0,56.0,45.0,25.0,15.0,9.0,10.0,8.0,2.0,84.0,41.0,35.0,27.0,15.0,1.0,2.0,304.0,NaN,75.0,NaN
2,3390,Adelaide,Hard,32,A,1990-12-31,3,101234,Patrik Kuhnen,R,190.0,24.8,101421,Veli Paloheimo,R,183.0,23.0,6-0 6-4,3,R32,71.0,6.0,1.0,54.0,31.0,24.0,13.0,8.0,1.0,1.0,2.0,2.0,60.0,37.0,22.0,6.0,8.0,4.0,8.0,82.0,NaN,69.0,NaN
3,3390,Adelaide,Hard,32,A,1990-12-31,4,101889,Todd Woodbridge,R,178.0,19.7,101703,Guillaume Raoux,R,180.0,20.8,7-6(2) 6-1,3,R32,85.0,2.0,0.0,60.0,40.0,30.0,14.0,9.0,3.0,3.0,3.0,3.0,74.0,45.0,30.0,11.0,10.0,5.0,8.0,50.0,NaN,84.0,NaN
4,3390,Adelaide,Hard,32,A,1990-12-31,5,101274,Udo Riglewski,R,185.0,24.4,101843,Sergi Bruguera,R,188.0,19.9,7-5 6-3,3,R32,90.0,4.0,2.0,72.0,40.0,33.0,14.0,10.0,7.0,8.0,2.0,2.0,77.0,41.0,28.0,15.0,11.0,4.0,8.0,88.0,NaN,28.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3071,4320,Davis Cup World Group 2,Clay,4,D,2024-02-03,5,212051,Joaquin Aguilar Cardozo,U,NaN,18.8,209943,Ilya Snitari,R,188.0,21.8,6-1 6-0,3,RR,77.0,0.0,0.0,36.0,22.0,15.0,10.0,7.0,1.0,1.0,1.0,1.0,61.0,30.0,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0
3072,4320,Davis Cup World Group 2,Hard,4,D,2024-02-02,1,122533,Nam Hoang Ly,R,175.0,26.9,202475,Philip Henning,R,NaN,23.2,6-3 6-4,3,RR,131.0,1.0,1.0,86.0,60.0,40.0,13.0,10.0,8.0,9.0,2.0,1.0,56.0,41.0,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0
3073,4320,Davis Cup World Group 2,Hard,4,D,2024-02-02,2,144748,Kris Van Wyk,R,185.0,27.3,144775,Linh Giang Trinh,R,183.0,26.4,4-6 6-3 4-0,3,RR,131.0,4.0,2.0,76.0,46.0,32.0,10.0,12.0,6.0,11.0,0.0,2.0,71.0,51.0,25.0,7.0,11.0,5.0,12.0,416.0,109.0,NaN,NaN
3074,4320,Davis Cup World Group 2,Hard,4,D,2024-02-02,4,122533,Nam Hoang Ly,R,175.0,26.9,144748,Kris Van Wyk,R,185.0,27.3,6-4 3-6 6-3,3,RR,159.0,0.0,1.0,84.0,61.0,41.0,13.0,14.0,2.0,5.0,5.0,3.0,86.0,51.0,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0
3075,4320,Davis Cup World Group 2,Hard,4,D,2024-02-02,5,202475,Philip Henning,R,NaN,23.2,144775,Linh Giang Trinh,R,183.0,26.4,6-2 6-2,3,RR,101.0,1.0,0.0,47.0,28.0,21.0,11.0,8.0,0.0,1.0,0.0,0.0,71.0,53.0,25.0,8.0,8.0,9.0,14.0,748.0,32.0,NaN,NaN

4. Check Format

In [10]:
def check_tourney_id_format(df):
    """
    Check for tourney_id values with hyphens, non-alphanumeric characters, or longer than 5 characters
    """
    issues_list = []
    
    for idx, row in df.iterrows():
        tourney_id = row['tourney_id']
        tourney_name = row['tourney_name']
        
        if pd.isna(tourney_id):
            issues_list.append([idx, tourney_id, tourney_name, "Missing/NaN value"])
            continue
            
        tourney_id_str = str(tourney_id)
        
        # Check for hyphens
        if '-' in tourney_id_str:
            issues_list.append([idx, tourney_id, tourney_name, "Contains hyphen"])
            continue
            
        # Check for non-alphanumeric characters
        if not tourney_id_str.isalnum():
            issues_list.append([idx, tourney_id, tourney_name, "Contains non-alphanumeric characters"])
            continue
            
        # Check length
        if len(tourney_id_str) > 5:
            issues_list.append([idx, tourney_id, tourney_name, "Longer than 5 characters"])
            continue
    
    # Convert to DataFrame
    if issues_list:
        format_issues_df = pd.DataFrame(issues_list, columns=['row_index', 'tourney_id', 'tourney_name', 'issue'])
    else:
        format_issues_df = pd.DataFrame(columns=['row_index', 'tourney_id', 'tourney_name', 'issue'])
    
    return format_issues_df

# Check format issues
format_issues = check_tourney_id_format(jeff_data)

print(f"Total format issues found: {len(format_issues)}")

Total format issues found: 0

In [11]:
def check_tourney_id_compatibility(df):
    """
    Check if tourney_id values are compatible with Main_Matches_Dataset_Pipeline validation.
    The pipeline tries to convert to numeric with errors='coerce', which creates nulls for non-numeric values.
    """
    issues_list = []
    
    for idx, row in df.iterrows():
        tourney_id = row['tourney_id']
        tourney_name = row['tourney_name']
        
        if pd.isna(tourney_id):
            issues_list.append([idx, tourney_id, tourney_name, "Missing/NaN value"])
            continue
        
        tourney_id_str = str(tourney_id)
        
        # Check if it's purely numeric (can be converted to int/float without loss)
        try:
            numeric_value = pd.to_numeric(tourney_id_str, errors='coerce')
            if pd.isna(numeric_value):
                issues_list.append([idx, tourney_id_str, tourney_name, "Cannot be converted to numeric (would become NULL in pipeline)"])
        except:
            issues_list.append([idx, tourney_id_str, tourney_name, "Conversion error"])
    
    if issues_list:
        compatibility_issues_df = pd.DataFrame(issues_list, columns=['row_index', 'tourney_id', 'tourney_name', 'issue'])
    else:
        compatibility_issues_df = pd.DataFrame(columns=['row_index', 'tourney_id', 'tourney_name', 'issue'])
    
    return compatibility_issues_df

# Check compatibility
compatibility_issues = check_tourney_id_compatibility(jeff_data)

print(f"Total compatibility issues found: {len(compatibility_issues)}")
if len(compatibility_issues) > 0:
    print("\nSample issues:")
    print(compatibility_issues.head(20))
    
    # Show unique tourney_ids that have issues
    print(f"\nUnique problematic tourney_ids: {compatibility_issues['tourney_id'].nunique()}")
    print(compatibility_issues[['tourney_id', 'tourney_name']].drop_duplicates())

Total compatibility issues found: 0

### Reformat Columns

In [12]:
def rename_columns(df):
    col_map = {}
    for col in df.columns:
        new_col = col
        # Replace 'winner' with 'player1', 'loser' with 'player2'
        new_col = new_col.replace('winner', 'player1').replace('loser', 'player2')
        # Replace 'w_' with 'p1_', 'l_' with 'p2_'
        if new_col.startswith('w_'):
            new_col = new_col.replace('w_', 'p1_')
        if new_col.startswith('l_'):
            new_col = new_col.replace('l_', 'p2_')
        col_map[col] = new_col
    return df.rename(columns=col_map)
jeff_data = rename_columns(jeff_data)

jeff_data['source'] = 0
jeff_data = jeff_data.reindex(columns=['tourney_name', 'tourney_id', 'tourney_date', 'tourney_level', 'surface', 'draw_size', 'match_num', 'round', 'best_of', 'minutes', 'player1_id', 'player1_name', 'player2_id', 'player2_name', 'player1_rank', 'player1_atp_points', 'player2_rank', 'player2_atp_points', 'player1_ht', 'player1_hand', 'player2_ht', 'player2_hand', 'p1_ace', 'p2_ace', 'p1_df', 'p2_df', 'p1_SvGms', 'p2_SvGms', 'p1_1stIn', 'p2_1stIn', 'p1_1stWon', 'p2_1stWon', 'p1_2ndWon', 'p2_2ndWon', 'p1_svpt', 'p2_svpt', 'p1_bpSaved', 'p2_bpSaved', 'p1_bpFaced', 'p2_bpFaced', 'score'], copy=False)

jeff_data.tail()

,tourney_name,tourney_id,tourney_date,tourney_level,surface,draw_size,match_num,round,best_of,minutes,player1_id,player1_name,player2_id,player2_name,player1_rank,player1_atp_points,player2_rank,player2_atp_points,player1_ht,player1_hand,player2_ht,player2_hand,p1_ace,p2_ace,p1_df,p2_df,p1_SvGms,p2_SvGms,p1_1stIn,p2_1stIn,p1_1stWon,p2_1stWon,p1_2ndWon,p2_2ndWon,p1_svpt,p2_svpt,p1_bpSaved,p2_bpSaved,p1_bpFaced,p2_bpFaced,score
3071,Davis Cup World Group 2,432,2024-02-03,D,Clay,4,5,RR,3,77.0,212051,Joaquin Aguilar Cardozo,209943,Ilya Snitari,1109.0,8.0,740.0,34.0,NaN,U,188.0,R,0.0,1.0,0.0,1.0,7.0,6.0,22.0,30.0,15.0,17.0,10.0,7.0,36.0,61.0,1.0,8.0,1.0,14.0,6-1 6-0
3072,Davis Cup World Group 2,432,2024-02-02,D,Hard,4,1,RR,3,131.0,122533,Nam Hoang Ly,202475,Philip Henning,554.0,67.0,748.0,32.0,175.0,R,NaN,R,1.0,2.0,1.0,1.0,10.0,9.0,60.0,41.0,40.0,25.0,13.0,6.0,86.0,56.0,8.0,1.0,9.0,4.0,6-3 6-4
3073,Davis Cup World Group 2,432,2024-02-02,D,Hard,4,2,RR,3,131.0,144748,Kris Van Wyk,144775,Linh Giang Trinh,416.0,109.0,NaN,NaN,185.0,R,183.0,R,4.0,0.0,2.0,2.0,12.0,11.0,46.0,51.0,32.0,25.0,10.0,7.0,76.0,71.0,6.0,5.0,11.0,12.0,4-6 6-3 4-0
3074,Davis Cup World Group 2,432,2024-02-02,D,Hard,4,4,RR,3,159.0,122533,Nam Hoang Ly,144748,Kris Van Wyk,554.0,67.0,416.0,109.0,175.0,R,185.0,R,0.0,5.0,1.0,3.0,14.0,14.0,61.0,51.0,41.0,32.0,13.0,17.0,84.0,86.0,2.0,5.0,5.0,9.0,6-4 3-6 6-3
3075,Davis Cup World Group 2,432,2024-02-02,D,Hard,4,5,RR,3,101.0,202475,Philip Henning,144775,Linh Giang Trinh,748.0,32.0,NaN,NaN,NaN,R,183.0,R,1.0,0.0,0.0,0.0,8.0,8.0,28.0,53.0,21.0,25.0,11.0,8.0,47.0,71.0,0.0,9.0,1.0,14.0,6-2 6-2

In [13]:
jeff_data['source'] = 0

### Export for General Match Dataset Processing

In [14]:
jeff_data.to_csv("./data/PreCleanedMatches/JeffSackmann.csv", index=False)